### ISSUE TITLE
Improve hiring process

### ISSUE THREAD

**Issue by zpatrick** [quintilesims/slackbot#22]
We need a command (or suite of commands) that helps with the hiring process. We currently have the !interview command that sets some reminders, but this can be revised/changed in order to better accommodate a larger set of features.

**Comment by andycmaj** [comment]
here are some scenarios based around the idea of a Pipeline for a candidate

at any step in the pipeline, we can bail out (decide not to proceed with the candidate).
steps in the pipeline, at the simplest level, might look like:

1. start pipeline
1. review resume
1. send take-home question
1. review take-home question
1. schedule a loop
1. loop
1. decide on candidate

## Start a new pipeline for a new candidate

* action

```bash
me: !candidate add phil@genesis.com Phil Collins

bot: thanks! added Phil. Next step is to review his/her resume.
```

* periodic reminder

```bash
bot: hello! someone still needs to review Phil Collins's resume!
```

> question: how to prompt for a resume upload?

## Move a candidate to next step in pipeline

* action (Approve resume, move on to take-home question)

```bash
me: !candidate status Phil Collins

bot: review Phil Collins's resume.

me: !candidate continue Phil Collins

bot: ok! time to send Phil Collins the take-home question
```

## Move a candidate to a step that requires input

```bash
me: !candidate status Phil Collins

bot: schedule an in-person loop

me: !candidate continue Phil Collins

bot: ok! time to schedule an in-person loop!
bot: <prompts for loop data (time/interviewers?)>

...?
```

## Bail out of a pipeline

```bash
me: !candidate status Phil Collins

bot: schedule an in-person loop

me: !candidate bail Phil Collins

bot: are you sure? yes/no?

me: yes

bot: ok sorry Phil Collins didn't work out.
```

**Comment by zpatrick** [comment]
Perhaps we should start with an overview of the current processes and see where slackbot could make things easier:

1. Interview Process
    a) Set 1-many dates for interviews for a candidate
    b) For each interview date, schedule 1-many interviews at a specific time with 1-many interviewers (e.g. John Doe interviews with Jane Doe on 03/22 at 09:15AM) 
    c) Prior to each interview, each interviewer needs to do some prep-work (typically, review the candidate's resume)
    d) Actually do the interview
    e) During/after each interview, each interviewer needs to record the interviewee's performance
    f) After all interviews have finished, aggregate all of the interviewers' scores and determine next course of action (hire, drop, or do another round of interviews). 
2. Hiring Process
    a) I don't know all of the specific actions here, but from what I understand, it's essentially just a long checklist of items for a manager to complete.

**Comment by andycmaj** [comment]
one consideration here is that this needs to work for teams with slightly different pipeline definitions.

i wonder if we could do something based on some kind of DSL:

```yaml
pipeline:
  team: oce-mcm
  steps:
  - name: review resume
  - name: send take-home question
  - name: review take-home question
  - name: schedule a loop
     prompts: 
     - name: interviewers
        type: loop-interviewers (highly hand-wavy and probably a terrible config API)
  - name: loop
  - name: decide on candidate
```

```yaml
pipeline:
  team: carbon
  steps:
  - name: send take-home question
  - name: review take-home question
  - name: schedule a loop
     prompts: 
     - name: interviewers
        type: loop-interviewers (highly hand-wavy and probably a terrible config API)
  - name: review resume
  - name: loop
  - name: decide on candidate
```

maybe each step has a pre-defined handler in code that understands how to prompt/remind/follow up/etc.
